volumes:
  elasticsearch:

services:
  elasticsearch:
    image: elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
    volumes:
        - "elasticsearch:/usr/share/elasticsearch/data"
    mem_limit: "1g"
  
  kibana:
    image: kibana:7.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5101:5601"
  
  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock